spring.application.name=study-matching-api

spring.jpa.hibernate.ddl-auto=validate
spring.jpa.open-in-view=false
spring.jpa.properties.hibernate.format_sql=true

spring.flyway.enabled=true

server.port=${SERVER_PORT:8080}

jwt.secret=${JWT_SECRET}
jwt.access-token-expiration-seconds=${JWT_ACCESS_TOKEN_EXPIRATION_SECONDS:3600}